### ISSUE TITLE
Next API route misused

### ISSUE THREAD

**Issue by smakosh** [DevC-Casa/blablaconf.com#16]
## Details

Hi everyone! Good work on building the website in a short period of time! I noticed that a Next API route is being misused, if you're not going to use the `res, req` arguments any function under the `api/` folder accepts, then it's better to move it outside of the folder otherwise you will be triggering a serverless function without taking full advantages of it.

For reference: https://nextjs.org/docs/api-routes/introduction

**Comment by yjose** [comment]
Thank you @smakosh for Infos, will fix them ASAP

**Comment by yjose** [comment]
@smakosh  check #18
