### ISSUE TITLE
Enhancement: Add to Calendar button

### ISSUE THREAD

**Issue by soufianos01** [DevC-Casa/blablaconf.com#38]
One suggestion I have is to make an "add to calendar" button in each Talk Component. 

**Use Case:** 
Maybe after the exact time for a talk is known, this button will appear and by clicking on it, the user can add this slot (talk.time => talk.time+2hours) to its calendar.

**Existing solutions?**
There are some ready to use components for this suggestion. like [add-to-calendar](https://www.npmjs.com/package/react-add-to-calendar) by Jason Salzman.

**Design**
Maybe we could do it as a flip-card. By hovering over a Talk Card, the card will flip and the user can choose to add it to its favorite calendar.

**Comment by aboullaite** [comment]
Nice idea @soufianos01, thanks for sharing. We'll try to include this feature this week as we announce official agenda.
