### ISSUE TITLE
blablaconf throws an error when  trying to get the ticket! 

### ISSUE THREAD

**Issue by AWIXOR** [DevC-Casa/blablaconf.com#40]
After submitting an email to get the ticket from blablaconf it throws an `Uncaught FirebaseError`,
please review that!

**Comment by aboullaite** [comment]
@AWIXOR we can't reproduce this issue. Can you check if it still happens, and share with us any useful info (email, consol log, ...)

**Comment by AWIXOR** [comment]
Yesterday the app was returning a `FirebaseError`, today it seems to be working!
Am closing the issue.
Thanks!
