### ISSUE TITLE
Very Important Issue About Your Site!

### ISSUE THREAD

**Issue by LizaMagicBlock** [DevC-Casa/blablaconf.com#44]
Hello Engineers,

We are The Magic Block Group!

Your database has been hacked, and we have all the data...

Here is the deal, send 2 ETH to this address:
```
0x309E0Ef53dadC7336510Ce10D06194DC23F09868
```

(we have a backup)

Send the 2 ETH and we will give you back your clean database, and we will never target you again.

This is not a threat, but you should valuate people who trusted you and put they email in your website our GROUP may target them as well...

If you check ur DB, You will know what we did dog, we can target and spam people who TRUSTED you and put their email in your website.

Se send the 2 ETH, then we will give you back your clean database, and we will not target the people who trusted you.

We don't give a frenchman fuck, we need our 2 ETH then we will forget the people who TRUSTED you.

The Magic Block Group.
Cheers.

**Comment by LizaMagicBlock** [comment]
Here the ...
![image](https://user-images.githubusercontent.com/72951502/96324816-2a000700-1013-11eb-8494-752243607cc8.png)

**Comment by LizaMagicBlock** [comment]
We do not hask tiny targets, but one of the members did it.... that's why the group get involved!

**Comment by yjose** [comment]
Thank you for  Your information, This is a community initiative project  which means we did our best to make it as secure as we can, we are working to fix the issue and notify our users about this issue 🙏

**Comment by LizaMagicBlock** [comment]
OK! when you notify your users tell them to watch their back, you gonna pay with them! I'm gonna let our little guy who did this your response then I will handle the email list to our dark net partners...
Thank you for your input.
