### ISSUE TITLE
Countdown timer missing

### ISSUE THREAD

**Issue by Selharem** [DevC-Casa/blablaconf.com#51]
Hi everyone ! Thanks for your efforts, you're doing a great job!

I think you should add a countdown timer on the home section, that's gonna be cool.

- Example from **<a href="https://ieeextreme.org/">IEEEXtreme<a/>** page : 

![image](https://user-images.githubusercontent.com/44909504/136468853-df77c1f4-c82e-4c99-9475-d13045e99589.png)

- Another example : 

<p align="center">
  <img src="https://user-images.githubusercontent.com/44909504/136469236-0aa0de90-391b-451f-8962-999815a4a91e.png">
</p>

<p align="center">
  Reference: <a href="https://www.pinterest.cl/pin/181903272438014047/">Pinterest<a/>
</p>

**Comment by aboullaite** [comment]
Hello @Selharem,
Thanks for suggesting this. We're actually working on a new website and won't add any feature to this one :) 
Stay tuned
